import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { ThemeProvider } from '@/app/providers/theme-provider';
import { ReactNode } from 'react';
import Aside from '@/app/components/aside';
import { UserProvider } from '@/app/providers/user-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute='class'
      defaultTheme='system'
      enableSystem
      disableTransitionOnChange
    >
      <UserProvider>
        <SidebarProvider>
          <div className='flex'>
            <Aside />
            <div className='bg-primary w-[calc(100dvw-var(--sidebar-width))] p-6 h-screen'>
              {children}
            </div>
          </div>
        </SidebarProvider>
      </UserProvider>
    </ThemeProvider>
  );
}
